cavavin/models.py
# coding=utf-8

import hashlib
from cavavin.app import db
from flask import g
from voluptuous import All, Invalid, Coerce, Length, Range, Required, Schema

__all__ = ['User', 'Wine', 'Bottle', 'Country', 'Region', 'Rack']


class User(db.Model):
    """ Utilisateur """

    __tablename__ = u'user'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.Unicode, unique=True, nullable=False)
    firstname = db.Column(db.Unicode, nullable=False)
    lastname = db.Column(db.Unicode, nullable=False)
    _password = db.Column(db.Unicode, nullable=False)

    def get_password(self):
        return self._password

    def set_password(self, password):
        self._password = unicode(hashlib.md5(password).hexdigest())

    password = property(get_password, set_password)

    def __str__(self):
        return "%s %s" % (self.firstname, self.lastname)

    def to_dict(self):

        return {
            u'id': self.id,
            u'email': self.email,
            u'firstname': self.firstname,
            u'lastname': self.lastname
        }


class Wine(db.Model):
    """ Vin """

    __tablename__ = u'wine'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.Unicode, nullable=False)
    cuvee = db.Column(db.Unicode, nullable=True)
    vintage = db.Column(db.Integer, nullable=True)  # millesime
    category = db.Column(db.Unicode, nullable=False)
    type = db.Column(db.Unicode, nullable=False)

    country_id = db.Column(db.Integer, db.ForeignKey('country.id'), nullable=False)
    country = db.relationship('Country')

    region_id = db.Column(db.Integer, db.ForeignKey('region.id'), nullable=True)
    region = db.relationship('Region')

    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = db.relationship('User')


class Bottle(db.Model):
    """ Bouteille """

    __tablename__ = u'bottle'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    entrance_date = db.Column(db.Date, nullable=False)
    exit_date = db.Column(db.Date, nullable=True)
    size = db.Column(db.Unicode, nullable=False)
    purchase_location = db.Column(db.Unicode, nullable=True)
    price = db.Column(db.Float, nullable=True)
    row = db.Column(db.Integer, nullable=True)
    column = db.Column(db.Integer, nullable=True)

    wine_id = db.Column(db.Integer, db.ForeignKey('wine.id'), nullable=False)
    wine = db.relationship('Wine', backref='bottles')

    rack_id = db.Column(db.Integer, db.ForeignKey('rack.id'), nullable=True)
    rack = db.relationship('Rack', backref='bottles')


class Country(db.Model):
    """ Pays """

    __tablename__ = u'country'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.Unicode, nullable=False)

    def to_dict(self):

        return {
            u'id': self.id,
            u'name': self.name,
        }


class Region(db.Model):

    __tablename__ = u'region'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.Unicode, nullable=False)

    country_id = db.Column(db.Integer, db.ForeignKey('country.id'), nullable=False)
    country = db.relationship('Country')

    def to_dict(self):

        return {
            u'id': self.id,
            u'name': self.name,
        }


class Rack(db.Model):
    """ Casier """

    __tablename__ = u'rack'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.Unicode, nullable=False)
    height = db.Column(db.Integer, nullable=False)
    width = db.Column(db.Integer, nullable=False)

    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = db.relationship('User')

    @property
    def size(self):
        return u'%sx%s' % (self.height, self.width)

    @property
    def capacity(self):
        return self.height * self.width

    @classmethod
    def from_dict(cls, rack_data):

        def name_is_available(msg=None):
            def f(v):
                if Rack.query.filter_by(name=v).filter_by(user=g.user).count() > 0:
                    raise Invalid(msg or (u"Le nom %s est déjà utilisé" % v))
                return v
            return f

        rack_schema = Schema({
            Required('name'): All(Coerce(unicode), Length(min=1, msg=u"Veuillez saisir un nom pour ce casier"), name_is_available()),
            Required('height'): All(Coerce(int, msg=u"Veuillez saisir un nombre entier"), Range(min=1, msg=u"La valeur doit être supérieur à 1")),
            Required('width'): All(Coerce(int, msg=u"Veuillez saisir un nombre entier"), Range(min=1, msg=u"La valeur doit être supérieur à 1"))
        })

        rack_data = rack_schema(rack_data)

        return Rack(name=rack_data['name'],
                    height=rack_data['height'],
                    width=rack_data['width'])

cavavin/__init__.py
# coding=utf-8

cavavin/app.py
# coding=utf-8

from flask import Flask
import logging.config

from .config import DefaultConfig
from .extensions import db


def create_app(config=None):
    """Create a Flask app
    Using application factory like describe here :
    http://flask.pocoo.org/docs/0.10/patterns/appfactories/#app-factories
    """

    app = Flask(__name__)

    configure_app(app, config)
    configure_logging(app)
    configure_extensions(app)
    configure_crash_handler(app)

    register_blueprints(app)

    return app


def configure_extensions(app):
    """Configure extensions defined in mouse.extensions.py"""
    app.logger.info('configuring extensions')

    # flask-sqlalchemy
    db.app = app
    db.init_app(app)

    # Enable Foreign key constraint when using Sqlite
    if db.engine.name == 'sqlite':  # pragma: no cover
        from .extensions import sqlite_foreign_key_event, remove_warning_decimal_for_sqlite

        sqlite_foreign_key_event(app)
        remove_warning_decimal_for_sqlite(app)


def configure_app(app, config=None):
    """Load configuration

    The default configuration is overwritten by `config` or custom config
    located in app.cfg

    """
    app.logger.debug('Configuring application')

    app.config.from_object(DefaultConfig)

    if not config:  # pragma: no cover
        app.logger.debug('Load config from app.cfg')
        app.config.from_pyfile('../app.cfg', silent=True)
    else:
        app.logger.debug('Load config from %s' % config)
        app.config.from_pyfile(config)


def register_blueprints(app):
    """Register blueprints
    """
    app.logger.debug('Registering blueprints')

    from .controllers import register_all_blueprints
    register_all_blueprints(app)


def configure_crash_handler(app):  # pragma: no cover
    """Add handler for logging application severe errors, such as HTTP:500, uncatch Exception"""
    if not app.debug and not app.testing:
        app.logger.info('configuring crash handler')

        from werkzeug.exceptions import HTTPException
        import sys
        import traceback

        def error_handler(error):
            from flask import request

            if isinstance(error, HTTPException):
                description = error.get_description(request.environ)
                code = error.code
                name = error.name
            else:
                description = "Traceback de l'appel:\n\t---\n"
                (type_except, value, tb) = sys.exc_info()
                trace = "\t".join(traceback.format_exception(type_except, value, tb))
                description += trace
                code = 500
                name = 'Internal Server Error'

            msg = "Code:%s\n\tName:%s\n\tMessage:%s\n" % (code, name, description)
            app.logger.error(msg)
            return description, code

        # Catch error 500
        app.register_error_handler(500, error_handler)
        # Catch all Exception
        app.register_error_handler(Exception, error_handler)

        def log_uncaught_exceptions(ex_cls, ex, tb):
            app.logger.critical(''.join(traceback.format_tb(tb)))
            app.logger.critical('{0}: {1}'.format(ex_cls, ex))

        sys.excepthook = log_uncaught_exceptions


def overwrite_dict(src, ovw):
    """Overwrite a dict with another one.
    Existing keys will be overwritten. New keys are added
    """

    import collections
    for k, v in ovw.iteritems():
        if isinstance(v, collections.Mapping):
            r = overwrite_dict(src.get(k, {}), v)
            src[k] = r
        else:
            src[k] = ovw[k]
    return src


def configure_logging(app):  # pragma: no cover
    """Configure logging"""
    if app.testing:
        # Skip test mode. Just check standard output.
        return

    if 'LOGGING' in app.config:
        app.logger  # Needed to configure the Flask logger, so we can modify it after
        config_dict = app.config['LOGGING']

        if 'LOGGING_EXT' in app.config:
            config_dict = overwrite_dict(config_dict, app.config['LOGGING_EXT'])

        logging.config.dictConfig(config_dict)

cavavin/controllers/__init__.py
# coding=utf-8

from flask import redirect, url_for


def register_all_blueprints(app):
    """ Register all blueprints
    """
    from .countries import countries_bp
    from .racks import racks_bp
    from .users import users_bp
    from .wines import wines_bp

    app.register_blueprint(countries_bp, url_prefix='/countries')
    app.register_blueprint(racks_bp, url_prefix='/racks')
    app.register_blueprint(users_bp, url_prefix='/users')
    app.register_blueprint(wines_bp, url_prefix='/wines')

    @app.route('/', methods=['GET'])
    def home():
        return redirect(url_for('racks.list'))

cavavin/controllers/countries.py
# coding=utf-8

import json
from cavavin.models import Country, Region
from flask import Blueprint, make_response

countries_bp = Blueprint('countries', __name__)


@countries_bp.route('', methods=['GET'])
def get_all_countries():
    response = make_response(json.dumps([country.to_dict() for country in Country.query.all()]))
    response.status_code = 200
    response.mimetype = 'application/json'
    return response


@countries_bp.route('/<int:country_id>/regions', methods=['GET'])
def get_regions_in_country(country_id):
    response = make_response(json.dumps([region.to_dict() for region in Region.query.filter_by(country_id=country_id).all()]))
    response.status_code = 200
    response.mimetype = 'application/json'
    return response

cavavin/controllers/login.py
# coding=utf-8

import hashlib
from cavavin.models import User
from flask import Blueprint, flash, redirect, render_template, request, session, url_for

login_bp = Blueprint('login', __name__)


@login_bp.route('', methods=['GET'])
def form():
    if 'user' in session:
        return redirect(url_for('racks.list'))

    return render_template('login.html')


@login_bp.route('', methods=['POST'])
def login():

    email = request.form.get('email', None)
    password = request.form.get('password', u'')

    user = User.query.filter_by(email=email).filter_by(password=unicode(hashlib.md5(password).hexdigest())).first()
    if user is None:
        flash('Email ou mot de passe invalide')
        return redirect(url_for('.form'))

    session['user'] = user.to_dict()
    return redirect(url_for('racks.list'))

cavavin/controllers/racks.py
# coding=utf-8

from cavavin.app import db
from cavavin.models import Rack
from cavavin.security import is_logged_in
from flask import Blueprint, flash, g, redirect, render_template, request, url_for
from voluptuous import MultipleInvalid

racks_bp = Blueprint('racks', __name__)


@racks_bp.route('', methods=['GET'])
@is_logged_in()
def list():
    racks = Rack.query.filter_by(user=g.user).all()
    return render_template('racks.html', racks=racks)


def render_new_rack_form(rack_data={}, errors={}):
    return render_template('new_rack.html',
                           rack_data=rack_data,
                           errors=errors)


@racks_bp.route('/new', methods=['GET'])
@is_logged_in()
def new():
    return render_new_rack_form()


@racks_bp.route('', methods=['POST'])
@is_logged_in()
def add():
    try:
        rack = Rack.from_dict(request.form)
    except MultipleInvalid as multiple_invalid:
        errors = {}
        for error in multiple_invalid.errors:
            if error.path[0] in errors:
                errors[error.path[0]].append(error.msg)
            else:
                errors[error.path[0]] = [error.msg]

        flash(u"Impossible d'enregister ce casier<br/>Veuillez corriger les erreurs ci-dessous", "danger")
        return render_new_rack_form(request.form, errors)

    rack.user = g.user
    try:
        db.session.add(rack)
        db.session.commit()
    except:
        flash(u"""Une erreur innatendue s'est produite lors de l'enregistrement du casier.<br/>
                  Si le problème persiste, merci d'envoyer un mail à julien.seiler@gmail.com""",
              "danger")
        return render_new_rack_form(request.form)

    flash(u"Le casier %s a été enregistré avec succès" % rack.name, "success")
    return redirect(url_for("racks.list"))

cavavin/controllers/users.py
# coding=utf-8

import hashlib
from cavavin.models import User
from cavavin.security import is_logged_in
from flask import Blueprint, flash, redirect, render_template, request, session, url_for

users_bp = Blueprint('users', __name__)


@users_bp.route('/login', methods=['GET'])
def login_form():
    if 'user' in session:
        return redirect(url_for('racks.list'))

    return render_template('login.html')


@users_bp.route('/login', methods=['POST'])
def login():

    email = request.form.get('email', None)
    password = request.form.get('password', u'')

    user = User.query.filter_by(email=email).filter_by(_password=unicode(hashlib.md5(password).hexdigest())).first()
    if user is None:
        flash('Email ou mot de passe invalide')
        return redirect(url_for('.login_form'))

    session['user'] = user.to_dict()
    return redirect(url_for('racks.list'))


@users_bp.route('/logout', methods=['GET'])
@is_logged_in()
def logout():
    session.pop('user')
    return redirect(url_for('.login_form'))

cavavin/controllers/wines.py
# coding=utf-8

from cavavin.models import Wine
from cavavin.security import is_logged_in
from flask import Blueprint, g, render_template

wines_bp = Blueprint('wines', __name__)


@wines_bp.route('', methods=['GET'])
@is_logged_in()
def list():
    wines = Wine.query.filter_by(user=g.user).all()
    return render_template('wines.html', wines=wines)


def render_new_wine_form(wine_data={}, errors={}):
    return render_template('new_wine.html',
                           wine_data=wine_data,
                           errors=errors)


@wines_bp.route('/new', methods=['GET'])
@is_logged_in()
def new():
    return render_new_wine_form()

cavavin/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cavavin</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- cavavin -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/cavavin.css') }}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- 1. Load libraries -->
    <!-- IE required polyfills, in this exact order -->
    <script src="{{ url_for('static', filename='node_modules/es6-shim/es6-shim.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/systemjs/dist/system-polyfills.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/angular2/es6/dev/src/testing/shims_for_IE.js') }}"></script>

    <script src="{{ url_for('static', filename='node_modules/angular2/bundles/angular2-polyfills.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/systemjs/dist/system.src.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/rxjs/bundles/Rx.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/angular2/bundles/angular2.dev.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/angular2/bundles/http.dev.js') }}"></script>

    {% block head %}
    {% endblock %}
  </head>
  <body>

    {% set navigation_bar = [
        ('racks.list', 'Mes casiers'),
        ('wines.list', 'Mes vins')
    ] -%}

    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Cavavin</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        {% if g.user %}
        <div class="collapse navbar-collapse" id="navbar">
          <ul class="nav navbar-nav">
          {% for id, caption in navigation_bar %}
            <li{% if id == active_page %} class="active"{% endif%}>
              <a href="{{url_for(id)}}">{{ caption|e }}</a>
            </li>
          {% endfor %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> {{g.user}}<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li>
                  <a href="{{ url_for('users.logout') }}"><span class="glyphicon glyphicon-log-out"></span> Se déconnecter</a>
                </li>
              </ul>
            </li>

          </ul>
        </div><!-- /.navbar-collapse -->
        {% endif %}
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container-fluid">
      {% for category in ['success', 'danger', 'warning', 'info'] %}
      {% with messages = get_flashed_messages(category_filter=[category]) %}
        {% if messages %}
          {% autoescape false %}
          <div class="alert alert-{{category}} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <ul class="list-unstyled">
            {% for message in messages %}
                <li>{{message}}</li>
            {% endfor %}
            </ul>
          </div>
          {% endautoescape %}
        {% endif %}
      {% endwith %}
      {% endfor %}
    </div>

    <div class="container">
    {% block body %}
    {% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>
</html>

cavavin/templates/login.html
{% extends "base.html" %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Bienvenue sur Cavavin</h3>
        </div>

        <div class="panel-body">
          <form method="post" action="{{ url_for('users.login') }}">

            <fieldset>
              <div class="form-group has-feedback">
                <input class="form-control" name="email" type="text" placeholder="Votre adresse mail" required />
              </div>

              <div class="form-group has-feedback">
                <input class="form-control" name="password" type="password" placeholder="Votre mot de passe" required/>
              </div>

              <input type="submit" class="btn btn-lg btn-primary btn-block" value="Se connecter" />
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

cavavin/templates/new_rack.html
{% extends "base.html" %}

{% block body %}

<h2>Nouveau casier</h2>

<form action="{{url_for('racks.add')}}" method="post">

  <div class="form-group {% if 'name' in errors %}has-error{% endif %}">
    <label for="name">Nom</label>
    <input type="text" class="form-control" id="name" name="name" placeholder="Nom du casier" value="{{rack_data.name}}">
    {% if 'name' in errors %}
      <p class="help-block">{{errors['name']|join('<br/>')}}</p>
    {% endif %}
  </div>

  <div class="form-group {% if 'height' in errors %}has-error{% endif %}">
    <label for="name">Hauteur</label>
    <input type="text" class="form-control" id="height" name="height" placeholder="Hauteur (nombre entier)" value="{{rack_data.height}}">
    {% if 'height' in errors %}
      <p class="help-block">{{errors['height']|join('<br/>')}}</p>
    {% endif %}
  </div>

  <div class="form-group {% if 'width' in errors %}has-error{% endif %}">
    <label for="width">Largeur</label>
    <input type="text" class="form-control" id="width" name="width" placeholder="Largeur (nombre entier)" value="{{rack_data.width}}">
    {% if 'width' in errors %}
      <p class="help-block">{{errors['width']|join('<br/>')}}</p>
    {% endif %}
  </div>

  <a href="{{url_for('racks.list')}}" class="btn btn-default">Annuler</a>
  <button type="submit" class="btn btn-primary">Ajouter</button>

</form>

{% endblock %}

cavavin/templates/new_wine.html
{% extends "base.html" %}

{% block head %}
<!-- 2. Configure SystemJS -->
<script>
  System.config({
    packages: {
      '/static/app': {
        format: 'register',
        defaultExtension: 'js'
      }
    }
  });
  System.import('/static/app/location-chooser-bootstrap')
        .then(null, console.error.bind(console));
</script>
{% endblock %}

{% block body %}

<h2>Nouveau vin</h2>

<form action="#" method="post">

  <div class="form-group {% if 'name' in errors %}has-error{% endif %}">
    <label for="name">Nom*</label>
    <input type="text" class="form-control" id="name" name="name" placeholder="Nom du vin" value="{{wine_data.name}}">
    {% if 'name' in errors %}
      <p class="help-block">{{errors['name']|join('<br/>')}}</p>
    {% endif %}
  </div>

  <div class="form-group {% if 'cuvee' in errors %}has-error{% endif %}">
    <label for="cuvee">Cuvée</label>
    <input type="text" class="form-control" id="cuvee" name="cuvee" placeholder="Cuvée du vin" value="{{wine_data.cuvee}}">
    {% if 'cuvee' in errors %}
      <p class="help-block">{{errors['cuvee']|join('<br/>')}}</p>
    {% endif %}
  </div>

  <div class="form-group {% if 'vintage' in errors %}has-error{% endif %}">
    <label for="vintage">Millésime*</label>
    <input type="text" class="form-control" id="vintage" name="vintage" placeholder="Millésime" value="{{wine_data.vintage}}">
    {% if 'vintage' in errors %}
      <p class="help-block">{{errors['vintage']|join('<br/>')}}</p>
    {% endif %}
  </div>

  <div class="form-group {% if 'category' in errors %}has-error{% endif %}">
    <label for="category">Catégorie*</label>
    <select class="form-control" id="category" name="category">
    {% for category in categories %}
      <option value="{{category}}" {% if wine_data.category == category %}selected="selected"{% endif %}>{{category}}</option>
    {% endfor %}
    </select>
    {% if 'category' in errors %}
      <p class="help-block">{{errors['category']|join('<br/>')}}</p>
    {% endif %}
  </div>

  <div class="form-group {% if 'type' in errors %}has-error{% endif %}">
    <label for="type">Type*</label>
    <select class="form-control" id="type" name="type">
    {% for type in types %}
      <option value="{{type}}" {% if wine_data.type == type %}selected="selected"{% endif %}>{{type}}</option>
    {% endfor %}
    </select>
    {% if 'type' in errors %}
      <p class="help-block">{{errors['type']|join('<br/>')}}</p>
    {% endif %}
  </div>

  <location-chooser>Loading...</location-chooser>

  <a href="{{url_for('wines.list')}}" class="btn btn-default">Annuler</a>
  <button type="submit" class="btn btn-primary">Ajouter</button>

</form>

{% endblock %}

cavavin/templates/racks.html
{% extends "base.html" %}
{% set active_page = "racks.list" %}

{% block body %}

<div class="pull-right">
  <a class="btn btn-primary" href="{{url_for('racks.new')}}">Nouveau casier</a>
</div>
<h2>Mes casiers</h2>

<table class="table table-condensed table-striped table-hover">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Dimension</th>
      <th>Utilisation</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for rack in racks %}
    <tr>
      <td>{{rack.name}}</td>
      <td>{{rack.size}}</td>
      <td>{{rack.bottles|length}}/{{rack.capacity}} bouteilles</td>
      <td></td>
    </tr>
    {% else %}
    <tr>
      <td colspan="4" class="text-center">
        Aucun casier<br/>
        <a href="{{url_for('racks.new')}}">Créer un nouveau casier</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

cavavin/templates/wines.html
{% extends "base.html" %}
{% set active_page = "wines.list" %}

{% block body %}

<div class="pull-right">
  <a class="btn btn-primary" href="{{ url_for('wines.new') }}">Nouveau vin</a>
</div>
<h2>Mes vins</h2>

<table class="table table-condensed table-striped table-hover">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Cuvée</th>
      <th>Millésime</th>
      <th>Catégorie</th>
      <th>Type</th>
      <th>Origine</th>
      <th>En stock</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for wine in wines %}
    <tr>
      <td>{{wine.name}}</td>
      <td>{{wine.cuvee}}</td>
      <td>{{wine.vintage}}</td>
      <td>{{wine.category}}</td>
      <td>{{wine.type}}</td>
      <td>{{wine.country.name}}{% if wine.region != None %}/{{wine.region.name}}{% endif %}</td>
      <td>{% if wine.bottles %}Oui{% else %}Nom{% endif %}</td>
      <td></td>
    </tr>
    {% else %}
    <tr>
      <td colspan="8" class="text-center">
        Aucun vin<br/>
        <a href="{{ url_for('wines.new') }}">Créer un nouveau vin</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}